CREATE TABLE person (
	Id INT(10) UNSIGNED NULL DEFAULT	NULL,
	FirstName VARCHAR(50) NULL DEFAULT NULL,
	LastName VARCHAR(50) NULL DEFAULT NULL,
	Addres VARCHAR(50) NULL DEFAULT NULL,
	Gender VARCHAR(50) NULL DEFAULT NULL
)
ENGINE=INNODB
;

ALTER TABLE person CHANGE id id INT(10) AUTO_INCREMENT PRIMARY KEY;